### ISSUE TITLE
Support for large networks?

### ISSUE THREAD

**Issue by PCK1992** [sduxbury/Key-players-in-Bipartite-Networks#1]
These functions look really cool and I tried them on my network but unfortunately, it did not work due to size. Do you plan on potentially expanding the functions to deal with larger networks?

**Comment by sduxbury** [comment]
I'd like to, but I don't see myself having the chance to do so in the near future, unfortunately. The approach uses so many projections that to make it scalable to really large networks would mean having to rewrite the method in a more efficient language than R. Unfortunately, I don't have the time to dive into that for the foreseeable future.
